"""Initial migration

Revision ID: 74f3b7c409cc
Revises: 
Create Date: 2026-04-18 06:48:59.926141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f3b7c409cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processing_time_seconds', sa.Float(), nullable=True))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_constraint(op.f('documents_owner_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_id_fkey'), 'documents', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.alter_column('documents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'processing_time_seconds')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'file_size_bytes')
    # ### end Alembic commands ###
